spring.datasource.url=jdbc:postgresql://dpg-crk2tkg8fa8c73fp2e6g-a.oregon-postgres.render.com/tododb_ctm4
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=todouser
spring.datasource.password=jMfO2QC5TcvSO37k0qBsEZWpLEWH3r4n
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate


#Spring security
jwt.secret=prodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkeyprodsecretkey
#Expiration time
jwt.expiration=3600000